### ISSUE TITLE
Check_Consistency.jar has classes in it's top-level directory

### ISSUE THREAD

**Issue by dwitman15** [negarq/darcy-artifact#1]
When running "java -jar Check_Consistency.jar", an error occurs due to the existence of class files at the root level of the jar. Perhaps the Check, Dependency, and DependenciesChecker classes need to go into a package within the jar, so that they aren't appearing at the root in an unnamed module.

`Exception in thread "main" java.lang.module.FindException: Unable to derive module descriptor for Check_Consistency.jar
        at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:647)
        at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:330)
        at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:283)
        at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:231)
        at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:189)
        at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:165)
        at DependenciesChecker.buildModuleDependencies(DependenciesChecker.java:60)
        at Check.main(Check.java:8)
Caused by: java.lang.module.InvalidModuleDescriptorException: Dependency.class found in top-level directory (unnamed package not allowed in module)
        at java.base/jdk.internal.module.ModulePath.toPackageName(ModulePath.java:719)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at java.base/jdk.internal.module.ModulePath.deriveModuleDescriptor(ModulePath.java:530)
        at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:643)
        ... 7 more
`

**Comment by negarq** [comment]
Regarding the Check_Consistency, it doesn't need to be inside your project. It will be fine just anywhere else. Let me check some items first:
Regarding the project you're trying to use Darcy for:
- Is it modularized? in a sense that there should be some modules, each including a module-info.java file and some packages. The module-info files could have only the module name and no directives inside, but they should exist.
For using Darcy:
- Do you have Java 9+ installed and used for running Darcy?
- What is the input you're giving to Darcy as your project path? Is it the path to the project directory or a specific package of it?
You could take a look at some of the sample projects we have in our dataset (darcy-artifact/Darcy/dataset_projects/) and see how they look like, and what the hierarchy of the files is. Note that, the path I use as an input to run Darcy is the path of each of the projects in the dataset (e.g. ../.../BunnyHop-master).

**Comment by dwitman15** [comment]
Currently, our project does not leverage JPMS and has no descriptor files, however it is modularized into packages. Our goal here is to use DARCY to help us understand what our module-info.java files should look like for each package. To start, I created one module-info.java file inside of a package, and wanted to run DARCY just to see what the output was. However I can go back and make files for each package and try to run again.

For your other two questions: 

- I am running openjdk 11.0.4. 
- I am providing the project path to the root directory of the project

**Comment by negarq** [comment]
The Check_consistency doesn't need to be in your root project. It should be fine anywhere. However, the reason of the error might be that you don't have module-info files for all your modules. Darcy assumes that your project is modularized and it can't find the module descriptors since your project is not using JPMS. So, I suggest that you run Darcy just for one of the projects in the database directory here (darcy-artifact/Darcy/dataset_projects/). If it runs with no error, you'll know that you have to first modularize your project just to have module-info files for all modules. If you still get the error, there might be something wrong with the way Check_Consistency is built. Please let me know the result. Thanks
